[project]
name = "py-pieces"
version = "2025.11.0"
description = "Python code pieces"
requires-python = ">=3.14"
dependencies = [
  "anyio>=4.11.0",
  "mcp[cli]>=1.21.0",
  "orjson>=3.11.4",
  "polars>=1.35.0",
  "pydantic>=2.12.4",
  "ruff>=0.14.4",
  "scikit-learn>=1.7.2",
  "trio>=0.32.0",
]
